name: 'Common Setup'
description: 'Set up JDK and grant execute permissions for gradlew'

inputs:
    java-version:
        description: 'Java version'
        required: true
        default: '22'

runs:
    using: 'composite'
    steps:
        -   name: Set up JDK
            uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
            with:
                java-version: ${{ inputs.java-version }}
                distribution: 'adopt'

        -   name: Verify JDK installation
            run: java -version
            shell: bash

        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew
            shell: bash
